version: 1.0.1000000.{build}
image: Visual Studio 2017
configuration: Release
install:
- cmd: git submodule update --init --recursive
- ps: >-
    dotnet --info
build_script:
- ps: .\build.ps1 -Target Appveyor
artifacts:
- path: .\artifacts\*.nupkg
- path: .\coverage-results\*
test: off
skip_commits:
  files:
    - readme.md
    - .gitignore
    - .editorconfig
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    branch: master
